### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by liulu112601** [orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch#7]
Hi 
I have a question about image loading in omniglot_dataset.py

Why use 1 -  array & why use transpose and reshape as below?

`https://github.com/orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch/blob/master/src/omniglot_dataset.py#L179-L180`

Thanks

**Comment by dnlcrl** [comment]
Hi, as the comment in line 12 of omniglot_dataset.py says, https://github.com/orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch/blob/8ed0c9a2de5a5281313927bd9db6ea592a23ec41/src/omniglot_dataset.py#L12
 
I took that implementation and used it, almost untouched, but my guess is that (you can also verify by placing a breakpoint in that part of the code) `x = 1.0 - torch.from_numpy(x)` is inverting the image range, so that what was black becomes white and viceversa. 

looking at the code I found the second line being more interesting tho: https://github.com/orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch/blob/8ed0c9a2de5a5281313927bd9db6ea592a23ec41/src/omniglot_dataset.py#L180

It looks like the transposition is useless, as it doesn't really apply a transposition (arguments are in order: 0, 1, so dimensions doesn't get swapped). It probably has to do with the memory management, as normally the `transpose` method should make the tensor non contiguous in memory, so that `contiguous` has to be called otherwise the `view` call would rise an error (here we could also use a `reshape()` instead of `contiguous().view()` ). Will investigate about `transpose(0, 1)` and will let you know if I find something.

**Comment by dnlcrl** [comment]
I was wrong, `transpose` takes two dimensions and swaps them, so it totally makes sense. while `contiguous().view(shape)` is because `view` works only with contiguous tensors, but it could be replaced with a `reshape(shape)`, which implicitly makes the tensor contiguous.

**Comment by ishgirwan** [comment]
Hello, I still couldn't understand what's the need for using transpose over here?

**Comment by d-li14** [comment]
@dnlcrl Any Update? Why is it necessary to swap these two dimensions?

**Comment by d-li14** [comment]
I see, because numpy and PIL load images in a row-first and column-first fashion respectively.
